# Generated by Django 5.0.6 on 2024-07-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
    ]
