# Generated by Django 5.0.6 on 2024-07-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapi', '0004_alter_account_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_no',
        ),
    ]
