# Generated by Django 5.0.6 on 2024-07-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapi', '0005_remove_account_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_no',
            field=models.CharField(default='0000', editable=False, max_length=250, unique=True),
        ),
    ]
