# Generated by Django 5.0.6 on 2024-07-02 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapi', '0007_alter_account_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(editable=False, max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)]),
        ),
    ]
